export const SAVED_LIST_ADD_ITEM = 'SAVED_LIST_ADD_ITEM';
export const SAVED_LIST_DELETE_ITEM = 'SAVED_LIST_DELETE_ITEM';

export const ISSUE_LIST_ADD_ITEM = 'ISSUE_LIST_ADD_ITEM';
export const ISSUE_LIST_UPDATE_ITEM = 'ISSUE_LIST_UPDATE_ITEM';

export const COMPLETE_LIST_ITEM = 'COMPLETE_LIST_ITEM';
